name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Executa uma vez por dia à meia-noite (UTC)
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permissão para fazer push
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar a cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: joaz0 # Troque pelo seu nome de usuário do GitHub
          outputs: |
            github-contribution-grid-snake.svg

      - name: Listar arquivos gerados
        run: ls -la

      - name: Commit e push manual
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b output || git checkout output
          git add .
          git commit -m "Atualizar cobrinha"
          git push origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
